using System.Text.Json;
using WinHome.Interfaces;

namespace WinHome.Services.Logging
{
    /// <summary>
    /// Implements an in-memory structured logger that aggregates operational tracking events into a list 
    /// and provides serialization support to output the entries as a structured JSON string.
    /// </summary>
    public class JsonLogger : ILogger
    {
        private readonly List<LogEntry> _logEntries = new();

        /// <summary>
        /// Appends a new operational log entry containing the specified message text and importance classification to the internal collection.
        /// </summary>
        /// <param name="message">The text contents or operational string descriptive detail to record.</param>
        /// <param name="level">The severity threshold determining how the message classification is categorized.</param>
        public void Log(string message, LogLevel level)
        {
            _logEntries.Add(new LogEntry(message, level));
        }

        /// <summary>
        /// Appends an error alert notice to the structured logs with a critical tracking severity level.
        /// </summary>
        /// <param name="message">The failure string details or exception message text to record.</param>
        public void LogError(string message)
        {
            Log(message, LogLevel.Error);
        }

        /// <summary>
        /// Appends a standard informational entry block to the structured logs using standard tracking metrics.
        /// </summary>
        /// <param name="message">The standard operational message track data contents to record.</param>
        public void LogInfo(string message)
        {
            Log(message, LogLevel.Info);
        }

        /// <summary>
        /// Appends a successful operation validation notice to the structured logs.
        /// </summary>
        /// <param name="message">The completion message validation confirmation text details to record.</param>
        public void LogSuccess(string message)
        {
            Log(message, LogLevel.Success);
        }

        /// <summary>
        /// Appends an explicit warning flag notification statement to the structured logs.
        /// </summary>
        /// <param name="message">The potential issue alert or operational warning detail context to record.</param>
        public void LogWarning(string message)
        {
            Log(message, LogLevel.Warning);
        }

        /// <summary>
        /// Serializes the entire collection of accumulated log entries into a cleanly formatted, indented JSON data representation string.
        /// </summary>
        /// <returns>A string containing the serialized log record blocks structured in valid JavaScript Object Notation format.</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(_logEntries, new JsonSerializerOptions { WriteIndented = true });
        }
    }

    /// <summary>
    /// Represents an immutable structure holding individual event log details, pairing message contexts with diagnostic level configurations.
    /// </summary>
    /// <param name="Message">The literal descriptive string content generated by the system event tracking process.</param>
    /// <param name="Level">The assigned operational tier context designating the event severity ranking.</param>
    public record LogEntry(string Message, LogLevel Level);
}